# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-03 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emaile',
            new_name='email',
        ),
    ]
